---
- name: Deploy Petclinic to Kubernetes Cluster
  hosts: qa
  become: yes
  vars:
    repo_dir: "/opt/spring-petclinic"
    image_tag_file: "image-tag.txt"

  tasks:

    # ----------------------------
    # FIX PERMISSION ISSUES FOREVER
    # ----------------------------

    - name: Ensure /opt/spring-petclinic exists and owned by ubuntu
      file:
        path: "{{ repo_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      become: yes

    # ----------------------------
    # Install git if not present
    # ----------------------------

    - name: Ensure git installed
      apt:
        name: git
        state: present
      become: yes

    # ----------------------------
    # Clone repo as ubuntu (NOT ROOT)
    # ----------------------------

    - name: Clone or update the repository
      git:
        repo: "https://github.com/Jeevan121/spring-petclinic.git"
        dest: "{{ repo_dir }}"
        version: main
        force: yes
      become: no       # clone as ubuntu user

    # ----------------------------
    # Pass dynamic Docker image tag from Jenkins
    # ----------------------------

    - name: Copy image-tag.txt from Jenkins workspace to remote host
      copy:
        src: "{{ image_tag_file }}"
        dest: "/tmp/image-tag.txt"
        mode: '0644'

    - name: Read image tag
      slurp:
        src: "/tmp/image-tag.txt"
      register: tag_raw

    - name: Set image tag
      set_fact:
        image_tag: "{{ tag_raw.content | b64decode | trim }}"

    - name: Debug image tag
      debug:
        msg: "Deploying image tag: {{ image_tag }}"

    # ----------------------------
    # Render Kubernetes Manifest (IMPORTANT FIX)
    # ----------------------------

    - name: Render petclinic manifest (controller → remote)
      template:
        src: "k8s/petclinic.yml.j2"                   # LOCAL path in Jenkins workspace
        dest: "{{ repo_dir }}/k8s/petclinic.yml"     # REMOTE path on K8s server
        mode: '0644'
      vars:
        image_tag: "{{ image_tag }}"
      become: no

    # ----------------------------
    # Apply DB manifest if exists
    # ----------------------------

    - name: Check if db.yaml exists
      stat:
        path: "{{ repo_dir }}/k8s/db.yml"
      register: db_file

    - name: Apply DB manifest if present
      command: kubectl apply -f {{ repo_dir }}/k8s/db.yml
      when: db_file.stat.exists

    # ----------------------------
    # Apply Petclinic Deployment
    # ----------------------------

    - name: Apply Petclinic manifest
      command: kubectl apply -f {{ repo_dir }}/k8s/petclinic.yml

    - name: Wait for rollout to complete
      command: kubectl rollout status deployment/petclinic --timeout=120s
      register: rollout_status
      failed_when: rollout_status.rc != 0

    # ----------------------------
    # Show Pod List
    # ----------------------------

    - name: Get pod status
      command: kubectl get pods -n default -o wide
      register: pod_status
      changed_when: false

    - name: Show pods
      debug:
        var: pod_status.stdout_lines
