---
- name: Deploy Petclinic to Kubernetes Cluster
  hosts: qa
  become: yes
  vars:
    repo_dir: "/opt/spring-petclinic"
    image_tag_file: "image-tag.txt"

  tasks:

    - name: Ensure git installed
      apt:
        name: git
        state: present
      become: yes

    - name: Clone or update the repository
      git:
        repo: "https://github.com/Jeevan121/spring-petclinic.git"
        dest: "{{ repo_dir }}"
        version: main
        force: yes

    - name: Copy image-tag.txt from Jenkins workspace to remote host
      copy:
        src: "{{ image_tag_file }}"
        dest: "/tmp/image-tag.txt"
        mode: '0644'

    - name: Read image tag
      slurp:
        src: "/tmp/image-tag.txt"
      register: tag_raw

    - name: Set image tag
      set_fact:
        image_tag: "{{ tag_raw.content | b64decode | trim }}"

    - name: Debug image tag
      debug:
        msg: "Deploying image tag: {{ image_tag }}"

    - name: Render petclinic manifest
      template:
        src: "{{ repo_dir }}/k8s/petclinic.yml.j2"
        dest: "{{ repo_dir }}/k8s/petclinic.yml"
        mode: '0644'
      vars:
        image_tag: "{{ image_tag }}"

    # SIMPLER CHECK — if db.yaml exists, apply it
    - name: Check if db.yaml exists
      stat:
        path: "{{ repo_dir }}/k8s/db.yaml"
      register: db_file

    - name: Apply DB manifest if present
      command: kubectl apply -f {{ repo_dir }}/k8s/db.yaml
      when: db_file.stat.exists

    - name: Apply Petclinic manifest
      command: kubectl apply -f {{ repo_dir }}/k8s/petclinic.yml

    - name: Wait for rollout to complete
      command: kubectl rollout status deployment/petclinic --timeout=120s
      register: rollout_status
      failed_when: rollout_status.rc != 0

    - name: Get pod status
      command: kubectl get pods -n default -o wide
      register: pod_status
      changed_when: false

    - name: Show pods
      debug:
        var: pod_status.stdout_lines
