---
- hosts: qa
  become: yes

  tasks:
    - name: Pull Petclinic Image
      command: docker pull jeevan121/petclinic:v1

    - name: Stop old container
      command: docker stop petclinic
      ignore_errors: yes

    - name: Remove old container
      command: docker rm petclinic
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name petclinic -p 8080:8080 jeevan121/petclinic:v1
